spring:
  application:
    name: TimeToGoBot
bot:
  username: ${TELEGRAM_BOT_USERNAME}
  token: ${TELEGRAM_BOT_TOKEN}
api:
  url: http://localhost:8080
  secret: ${API_SECRET}
server:
  port: 8082
management:
  server:
    port: 8079
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    tags:
      applicaton: ${spring.application.name}


