name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push crud
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./crud/Dockerfile
          push: true
          tags: suprimi4/crud-app:latest

      - name: Push bot
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./TimeToGoBot/Dockerfile
          push: true
          tags: suprimi4/time_to_go_bot:latest

  push_compose:
    name: Push docker-compose.yaml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yaml"
          target: ${{ secrets.TARGET_PATH }}
          overwrite: 'true'
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build_and_push_images, push_compose ]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET_PATH }}
            docker stop timeToGoBot-parent 
            docker container rm timeToGoBot-parent
            docker stop backend-app-parent
            docker container rm backend-app-parent
            docker pull suprimi4/crud-app:latest
            docker pull suprimi4/time_to_go_bot:latest
            docker compose up -d
            docker ps -a